openapi: 3.1.0
info:
  title: Kris API
  description: >-
    The BE service for Kris
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
  - url: http://localhost:8082
paths:
  /user:
    summary: Gets the information of the current user
    get:
      summary: Fetch current user
      operationId: GetUser
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
